# Generated by Django 4.1.2 on 2023-02-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='height',
        ),
        migrations.RemoveField(
            model_name='products',
            name='information',
        ),
        migrations.RemoveField(
            model_name='products',
            name='width',
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
