# Generated by Django 4.1.2 on 2023-02-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_remove_products_height_remove_products_information_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='size',
            new_name='siz',
        ),
    ]
