# Generated by Django 4.1.2 on 2023-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_rename_size_products_siz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='siz',
            new_name='size',
        ),
    ]
