# Generated by Django 4.1.2 on 2023-02-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_remove_contact_subject_contact_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='color',
            new_name='cutting_size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='products',
            name='material',
        ),
        migrations.RemoveField(
            model_name='products',
            name='size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='weight',
        ),
        migrations.AddField(
            model_name='products',
            name='delivery_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='flavour',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
